//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        public int NumeroIdentificacion { get; set; }
        public string TipoIdentificacion { get; set; }
        public string NombreCompleto { get; set; }
        public string Biblioteca { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Celular { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Municipio { get; set; }
        public string CorreoElectronico { get; set; }
        public string ServiciosPublicos { get; set; }
        public Nullable<int> DocumentoIdentidad { get; set; }
        public string Contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuentas { get; set; }
    }
}
