//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public bool Estado { get; set; }
        public int NumeroIdentificacionCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
